# Generated by Django 3.1.1 on 2020-09-19 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_vegetableinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vegetableinstance',
            options={'ordering': ['exp_date'], 'permissions': (('can_mark_returned', 'Set vegetable as returned'),)},
        ),
    ]
