# Generated by Django 3.1.1 on 2020-09-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200919_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='family',
            field=models.ManyToManyField(help_text='Select a family for this vegetable', to='catalog.Family'),
        ),
    ]
